platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

target 'MediaLoader_Example' do
  pod 'M2MediaLoader', :path => '../'

  target 'MediaLoader_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 3.0.0'
    pod 'Nimble', '~> 9.0.0-rc.3'
  end
end
